In [9]:
import numpy as np

a = np.array([[3, 3, 3], [1, 3, 4], [7, 1, 3]])
np.unique(a)

array([1, 3, 4, 7])

In [13]:
z = np.array([92, 13, 44, 555, 1, -3])
z[::-1][4]

13

In [21]:
b = np.full(shape = (5), fill_value = 1)
c = b * 2
np.dot(c, b)

10

In [37]:
d = np.array([[0, 9, 19, 13], [1, 20, 5, 13], [12, 11, 3, 4]])
e = np.array([[2, 0, 0 , 0], [1, 2, 2, 0], [2, 1, 1, 0], [0, 0, 1, 1]])
np.dot(d, e)

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [27]:
f = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])
f.mean()

4.875

In [28]:
from scipy import linalg

g = np.array([[6, 0, 3], [0, -1, 2], [12, 3, 0]])
linalg.det(g)

0.0

In [29]:
h = np.array([[1, -1, -1, 0], [-1, 2, -1, -1], [-1, -1, 2, -1], [0, -1, -1, 1]])
values, vectors = linalg.eig(h)
values

array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j])

In [1]:
#i = np.array([[2, 4, 0, 4, 1],
             [2, 4, 1, 1, 0],
             [1, 1, 1, 2, 2],
             [0, 1, 3, 2, 4],
             [2, 2, 2, 0, 2]])
#np.trace(linalg.inv(i))

NameError: name 'np' is not defined

In [5]:
import numpy as np

np.math.factorial(10)*1024/np.math.factorial(20)

1.5273493085670588e-09